name: Create Cypress report
on:
  push:
    branches:
      - "main"
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm ci

      - name: run tests
        run: npx cypress run --e2e --browser chrome
        continue-on-error: true

      - uses: actions/upload-artifact@v4.0.0
        with:
          name: index.html
          path: ./docs/index.html

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
permissions:
  contents: write
